branch-defaults:
  firebase:
    environment: null
    group_suffix: null
  master:
    environment: node-express-env
global:
  application_name: synchromabackend
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git
